CREATE TABLE `city` (
  `city_id` int(11) NOT NULL,
  `city_name` varchar(255) DEFAULT NULL,
  `province_id` int(11) DEFAULT NULL
);

INSERT INTO city (province_id, city_name) VALUES
  (1, 'Kabupaten Aceh Barat'),
  (1, 'Kabupaten Aceh Barat Daya'),
  (1, 'Kabupaten Aceh Besar'),
  (1, 'Kabupaten Aceh Jaya'),
  (1, 'Kabupaten Aceh Selatan'),
  (1, 'Kabupaten Aceh Singkil'),
  (1, 'Kabupaten Aceh Tamiang'),
  (1, 'Kabupaten Aceh Tengah'),
  (1, 'Kabupaten Aceh Tenggara'),
  (1, 'Kabupaten Aceh Timur'),
  (1, 'Kabupaten Aceh Utara'),
  (1, 'Kabupaten Bener Meriah'),
  (1, 'Kabupaten Bireuen'),
  (1, 'Kabupaten Gayo Lues'),
  (1, 'Kabupaten Nagan Raya'),
  (1, 'Kabupaten Pidie'),
  (1, 'Kabupaten Pidie Jaya'),
  (1, 'Kabupaten Simeuleu'),
  (1, 'Kota Banda Aceh'),
  (1, 'Kota Langsa'),
  (1, 'Kota Lhokseumawe'),
  (1, 'Kota Sabang'),
  (1, 'Kota Subulussalam');

INSERT INTO city (province_id, city_name) VALUES
  (2, 'Kabupaten Badung'),
  (2, 'Kabupaten Bangli'),
  (2, 'Kabupaten Buleleng'),
  (2, 'Kabupaten Gianyar'),
  (2, 'Kabupaten Jembrana'),
  (2, 'Kabupaten Karangasem'),
  (2, 'Kabupaten Klungkung'),
  (2, 'Kabupaten Tabanan'),
  (2, 'Kota Denpasar');

INSERT INTO city (province_id, city_name) VALUES
  (3, 'Kabupaten Lebak'),
  (3, 'Kabupaten Pandeglang'),
  (3, 'Kabupaten Serang'),
  (3, 'Kabupaten Tangerang'),
  (3, 'Kota Cilegon'),
  (3, 'Kota Serang'),
  (3, 'Kota Tangerang'),
  (3, 'Kota Tangerang Selatan');

INSERT INTO city (province_id, city_name) VALUES
  (4, 'Kabupaten Bengkulu Selatan'),
  (4, 'Kabupaten Bengkulu Tengah'),
  (4, 'Kabupaten Bengkulu Utara'),
  (4, 'Kabupaten Kaur'),
  (4, 'Kabupaten Keepahiang'),
  (4, 'Kabupaten Lebong'),
  (4, 'Kabupaten Mukomuko'),
  (4, 'Kabupaten Rejang Lebong'),
  (4, 'Kabupaten Seluma'),
  (4, 'Kota Bengkulu');

INSERT INTO city (province_id, city_name) VALUES
  (5, 'Kabupaten Boalemo'),
  (5, 'Kabupaten Bone Bolango'),
  (5, 'Kabupaten Gorontalo'),
  (5, 'Kabupaten Gorontalo Utara'),
  (5, 'Kabupaten Pohuwato'),
  (5, 'Kota Gorontalo');

INSERT INTO city (province_id, city_name) VALUES
  (6, 'Kabupaten Administrasi Kepulauan Seribu'),
  (6, 'Kota Administrasi Jakarta Barat'),
  (6, 'Kota Administrasi Jakarta Pusat'),
  (6, 'Kota Administrasi Jakarta Selatan'),
  (6, 'Kota Administrasi Jakarta Timur'),
  (6, 'Kota Administrasi Jakarta Utara');

INSERT INTO city (province_id, city_name) VALUES
  (7, 'Kabupaten Batanghari'),
  (7, 'Kabupaten Bungo'),
  (7, 'Kabupaten Kerinci'),
  (7, 'Kabupaten Merangin'),
  (7, 'Kabupaten Muaro Jambi'),
  (7, 'Kabupaten Sarolangun'),
  (7, 'Kabupaten Tanjung Jabung Barat'),
  (7, 'Kabupaten Tanjung Jabung Timur'),
  (7, 'Kabupaten Tebo'),
  (7, 'Kota Jambi'),
  (7, 'Kota Sungaioenuh');

INSERT INTO city (province_id, city_name) VALUES
  (8, 'Kabupaten Bandung'),
  (8, 'Kabupaten Bandung Barat'),
  (8, 'Kabupaten Bekasi'),
  (8, 'Kabupaten Bogor'),
  (8, 'Kabupaten Ciamis'),
  (8, 'Kabupaten Cianjur'),
  (8, 'Kabupaten Cirebon'),
  (8, 'Kabupaten Garut'),
  (8, 'Kabupaten Indramayu'),
  (8, 'Kabupaten Karawang'),
  (8, 'Kabupaten Kuningan'),
  (8, 'Kabupaten Majalengka'),
  (8, 'Kabupaten Pangandaran'),
  (8, 'Kabupaten Purwakarta'),
  (8, 'Kabupaten Subang'),
  (8, 'Kabupaten Sukabumi'),
  (8, 'Kabupaten Sumedang'),
  (8, 'Kabupaten Tasikmalaya'),
  (8, 'Kota Bandung'),
  (8, 'Kota Banjar'),
  (8, 'Kota Bekasi'),
  (8, 'Kota Bogor'),
  (8, 'Kota Cimahi'),
  (8, 'Kota Cirebon'),
  (8, 'Kota Depok'),
  (8, 'Kota Sukabumi'),
  (8, 'Kota Tasikmalaya');

INSERT INTO city (province_id, city_name) VALUES
  (9, 'Kabupaten Banjarnegara'),
  (9, 'Kabupaten Banyumas'),
  (9, 'Kabupaten Batang'),
  (9, 'Kabupaten Blora'),
  (9, 'Kabupaten Boyolali'),
  (9, 'Kabupaten Brebes'),
  (9, 'Kabupaten Cilacap'),
  (9, 'Kabupaten Demak'),
  (9, 'Kabupaten Grobogan'),
  (9, 'Kabupaten Jepara'),
  (9, 'Kabupaten Karanganyar'),
  (9, 'Kabupaten Kebumen'),
  (9, 'Kabupaten Kendal'),
  (9, 'Kabupaten Klaten'),
  (9, 'Kabupaten Kudus'),
  (9, 'Kabupaten Magelang'),
  (9, 'Kabupaten Pati'),
  (9, 'Kabupaten Pekalongan'),
  (9, 'Kabupaten Pemalang'),
  (9, 'Kabupaten Purbalingga'),
  (9, 'Kabupaten Purworejo'),
  (9, 'Kabupaten Rembang'),
  (9, 'Kabupaten Semarang'),
  (9, 'Kabupaten Sragen'),
  (9, 'Kabupaten Sukoharjo'),
  (9, 'Kabupaten Tegal'),
  (9, 'Kabupaten Temanggung'),
  (9, 'Kabupaten Wonogiri'),
  (9, 'Kabupaten Wonosobo'),
  (9, 'Kota Magelang'),
  (9, 'Kota Pekalongan'),
  (9, 'Kota Salatiga'),
  (9, 'Kota Semarang'),
  (9, 'Kota Surakarta'),
  (9, 'Kota Tegal');

INSERT INTO city (province_id, city_name) VALUES
  (10, 'Kabupaten Bangkalan'),
  (10, 'Kabupaten Banyuwangi'),
  (10, 'Kabupaten Blitar'),
  (10, 'Kabupaten Bojonegoro'),
  (10, 'Kabupaten Bondowoso'),
  (10, 'Kabupaten Gresik'),
  (10, 'Kabupaten Jember'),
  (10, 'Kabupaten Jombang'),
  (10, 'Kabupaten Kediri'),
  (10, 'Kabupaten Lamongan'),
  (10, 'Kabupaten Lumajang'),
  (10, 'Kabupaten Madiun'),
  (10, 'Kabupaten Magetan'),
  (10, 'Kabupaten Malang'),
  (10, 'Kabupaten Mojokerto'),
  (10, 'Kabupaten Nganjuk'),
  (10, 'Kabupaten Ngawi'),
  (10, 'Kabupaten Pacitan'),
  (10, 'Kabupaten Pamekasan'),
  (10, 'Kabupaten Pasuruan'),
  (10, 'Kabupaten Ponorogo'),
  (10, 'Kabupaten Probolinggo'),
  (10, 'Kabupaten Sampang'),
  (10, 'Kabupaten Sidoarjo'),
  (10, 'Kabupaten Situbondo'),
  (10, 'Kabupaten Sumenep'),
  (10, 'Kabupaten Trenggalek'),
  (10, 'Kabupaten Tuban'),
  (10, 'Kabupaten Tulungagung'),
  (10, 'Kota Batu'),
  (10, 'Kota Blitar'),
  (10, 'Kota Kediri'),
  (10, 'Kota Madiun'),
  (10, 'Kota Malang'),
  (10, 'Kota Mojokerto'),
  (10, 'Kota Pasuruan'),
  (10, 'Kota Probolinggo'),
  (10, 'Kota Surabaya');

INSERT INTO city (province_id, city_name) VALUES
  (11, 'Kabupaten Bengkayang'),
  (11, 'Kabupaten Kapuas Hulu'),
  (11, 'Kabupaten Kayong Utara'),
  (11, 'Kabupaten Ketapang'),
  (11, 'Kabupaten Kubu Raya'),
  (11, 'Kabupaten Landak'),
  (11, 'Kabupaten Melawi'),
  (11, 'Kabupaten Mempawah'),
  (11, 'Kabupaten Sambas'),
  (11, 'Kabupaten Sanggau'),
  (11, 'Kabupaten Sekadau'),
  (11, 'Kabupaten Sintang'),
  (11, 'Kota Pontianak'),
  (11, 'Kota Singkawang');

INSERT INTO city (province_id, city_name) VALUES
  (12, 'Kabupaten Balangan'),
  (12, 'Kabupaten Banjar'),
  (12, 'Kabupaten Barito Kuala'),
  (12, 'Kabupaten Hulu Sungai Selatan'),
  (12, 'Kabupaten Hulu Sungai Tengah'),
  (12, 'Kabupaten Hulu Sungai Utara'),
  (12, 'Kabupaten Kotabaru'),
  (12, 'Kabupaten Tabalong'),
  (12, 'Kabupaten Tanah Bumbu'),
  (12, 'Kabupaten Tanah Laut'),
  (12, 'Kabupaten Tapin'),
  (12, 'Kota Banjarbaru'),
  (12, 'Kota Banjarmasin');

INSERT INTO city (province_id, city_name) VALUES
  (13, 'Kabupaten Barito Selatan'),
  (13, 'Kabupaten Barito Timur'),
  (13, 'Kabupaten Barito Utara'),
  (13, 'Kabupaten Gunung Mas'),
  (13, 'Kabupaten Kapuas'),
  (13, 'Kabupaten Katingan'),
  (13, 'Kabupaten Kotawaringin Barat'),
  (13, 'Kabupaten Kotawaringin Timur'),
  (13, 'Kabupaten Lamandau'),
  (13, 'Kabupaten Murung Raya'),
  (13, 'Kabupaten Pulang Pisau'),
  (13, 'Kabupaten Sukamara'),
  (13, 'Kabupaten Seruyan'),
  (13, 'Kota Palangka Raya');

INSERT INTO city (province_id, city_name) VALUES
  (14, 'Kabupaten Berau'),
  (14, 'Kabupaten Kutai Barat'),
  (14, 'Kabupaten Kutai Kartanegara'),
  (14, 'Kabupaten Kutai Timur'),
  (14, 'Kabupaten Mahakam Ulu'),
  (14, 'Kabupaten Paser'),
  (14, 'Kabupaten Penajam Paser Utara'),
  (14, 'Kota Balikpapan'),
  (14, 'Kota Bontang'),
  (14, 'Kota Samarinda');

INSERT INTO city (province_id, city_name) VALUES
  (15, 'Kabupaten Bulungan'),
  (15, 'Kabupaten Malinau'),
  (15, 'Kabupaten Nunukan'),
  (15, 'Kabupaten Tana Tidung'),
  (15, 'Kota Tarakan');

INSERT INTO city (province_id, city_name) VALUES
  (16, 'Kabupaten Bangka'),
  (16, 'Kabupaten Bangka Barat'),
  (16, 'Kabupaten Bangka Selatan'),
  (16, 'Kabupaten Bangka Tengah'),
  (16, 'Kabupaten Belitung'),
  (16, 'Kabupaten Belitung Timur'),
  (16, 'Kota Pangkal Pinang');

INSERT INTO city (province_id, city_name) VALUES
  (17, 'Kabupaten Bintan Kepulauan'),
  (17, 'Kabupaten Karimun'),
  (17, 'Kabupaten Kepulauan Anambas'),
  (17, 'Kabupaten Lingga'),
  (17, 'Kabupaten Natuna'),
  (17, 'Kota Batam'),
  (17, 'Kota Tanjung Pinang');

INSERT INTO city (province_id, city_name) VALUES
  (18, 'Kabupaten Lampung Barat'),
  (18, 'Kabupaten Lampung Selatan'),
  (18, 'Kabupaten Lampung Tengah'),
  (18, 'Kabupaten Lampung Timur'),
  (18, 'Kabupaten Lampung Utara'),
  (18, 'Kabupaten Mesuji'),
  (18, 'Kabupaten Pesawaran'),
  (18, 'Kabupaten Pesisir Barat'),
  (18, 'Kabupaten Pringsewu'),
  (18, 'Kabupaten Tanggamus'),
  (18, 'Kabupaten Tulang Bawang'),
  (18, 'Kabupaten Tulang Bawang Barat'),
  (18, 'Kabupaten Way Kanan'),
  (18, 'Kota Bandar Lampung'),
  (18, 'Kota Metro');

INSERT INTO city (province_id, city_name) VALUES
  (19, 'Kabupaten Buru'),
  (19, 'Kabupaten Buru Selatan'),
  (19, 'Kabupaten Kepulauan Aru'),
  (19, 'Kabupaten Maluku Barat Daya'),
  (19, 'Kabupaten Maluku Tengah'),
  (19, 'Kabupaten Maluku Tenggara'),
  (19, 'Kabupaten Maluku Tenggara Barat'),
  (19, 'Kabupaten Seram Bagian Barat'),
  (19, 'Kabupaten Seram Bagian Timur'),
  (19, 'Kota Ambon'),
  (19, 'Kota Tuai');

INSERT INTO city (province_id, city_name) VALUES
  (20, 'Kabupaten Halmahera Barat'),
  (20, 'Kabupaten Halmahera Tengah'),
  (20, 'Kabupaten Halmahera Timur'),
  (20, 'Kabupaten Halmahera Selatan'),
  (20, 'Kabupaten Halmahera Utara'),
  (20, 'Kabupaten Kepulauan Sula'),
  (20, 'Kabupaten Pulau Morotai'),
  (20, 'Kabupaten Pulau Taliabu'),
  (20, 'Kota Ternate'),
  (20, 'Kota Tidore Kepulauan');

INSERT INTO city (province_id, city_name) VALUES
  (21, 'Kabupaten Bima'),
  (21, 'Kabupaten Dompu'),
  (21, 'Kabupaten Lombok Barat'),
  (21, 'Kabupaten Lombok Tengah'),
  (21, 'Kabupaten Lombok Timur'),
  (21, 'Kabupaten Lombok Utara'),
  (21, 'Kabupaten Sumbawa'),
  (21, 'Kabupaten Sumbawa Barat'),
  (21, 'Kota Bima'),
  (21, 'Kota Mataram');

INSERT INTO city (province_id, city_name) VALUES
  (22, 'Kabupaten Alor'),
  (22, 'Kabupaten Belu'),
  (22, 'Kabupaten Ende'),
  (22, 'Kabupaten Flores Timur'),
  (22, 'Kabupaten Kupang'),
  (22, 'Kabupaten Lembata'),
  (22, 'Kabupaten Malaka'),
  (22, 'Kabupaten Manggarai'),
  (22, 'Kabupaten Manggarai Barat'),
  (22, 'Kabupaten Manggarai Timur'),
  (22, 'Kabupaten Ngada'),
  (22, 'Kabupaten Nagekeo'),
  (22, 'Kabupaten Rote Ndao'),
  (22, 'Kabupaten Sabu Raijua'),
  (22, 'Kabupaten Sikka'),
  (22, 'Kabupaten Sumba Barat'),
  (22, 'Kabupaten Sumba Barat Daya'),
  (22, 'Kabupaten Sumba Tengah'),
  (22, 'Kabupaten Sumba Timur'),
  (22, 'Kabupaten Timor Tengah Selatan'),
  (22, 'Kabupaten Timor Tengah Utara'),
  (22, 'Kabupaten Kupang');

INSERT INTO city (province_id, city_name) VALUES
  (23, 'Kabupaten Asmat'),
  (23, 'Kabupaten Biak Numfor'),
  (23, 'Kabupaten Boven Digoel'),
  (23, 'Kabupaten Deiyai'),
  (23, 'Kabupaten Dogiyai'),
  (23, 'Kabupaten Intan Jaya'),
  (23, 'Kabupaten Jayapura'),
  (23, 'Kabupaten Jayawijaya'),
  (23, 'Kabupaten Keerom'),
  (23, 'Kabupaten Kepulauan Yapen'),
  (23, 'Kabupaten Lannya Jaya'),
  (23, 'Kabupaten Mamberamo Raya'),
  (23, 'Kabupaten Mamberamo Tengah'),
  (23, 'Kabupaten Mappi'),
  (23, 'Kabupaten Merauke'),
  (23, 'Kabupaten Mimika'),
  (23, 'Kabupaten Nabire'),
  (23, 'Kabupaten Nduga'),
  (23, 'Kabupaten Paniai'),
  (23, 'Kabupaten Pegunungan Bintang'),
  (23, 'Kabupaten Puncak'),
  (23, 'Kabupaten Puncak Jaya'),
  (23, 'Kabupaten Sarmi'),
  (23, 'Kabupaten Supiori'),
  (23, 'Kabupaten Tolikara'),
  (23, 'Kabupaten Waropen'),
  (23, 'Kabupaten Yahukimo'),
  (23, 'Kabupaten Yalimo'),
  (23, 'Kota Jayapura');

INSERT INTO city (province_id, city_name) VALUES
  (24, 'Kabupaten Fakfak'),
  (24, 'Kabupaten Kaimana'),
  (24, 'Kabupaten Manokwari'),
  (24, 'Kabupaten Manokwari Selatan'),
  (24, 'Kabupaten Maybrat'),
  (24, 'Kabupaten Pegunungan Arfak'),
  (24, 'Kabupaten Raja Ampat'),
  (24, 'Kabupaten Sorong'),
  (24, 'Kabupaten Sorong Selatan'),
  (24, 'Kabupaten Tambrauw'),
  (24, 'Kabupaten Teluk Bintuni'),
  (24, 'Kabupaten Teluk Wondama'),
  (24, 'Kota Sorong');

INSERT INTO city (province_id, city_name) VALUES
  (25, 'Kabupaten Bengkalis'),
  (25, 'Kabupaten Indragiri Hilir'),
  (25, 'Kabupaten Indragiri Hulu'),
  (25, 'Kabupaten Kampar'),
  (25, 'Kabupaten Kepulauan Meranti'),
  (25, 'Kabupaten Kuantan Singingi'),
  (25, 'Kabupaten Pelalawan'),
  (25, 'Kabupaten Rokan Hilir'),
  (25, 'Kabupaten Rokan Hulu'),
  (25, 'Kabupaten Siak'),
  (25, 'Kota Dumai'),
  (25, 'Kota Pekanbaru');

INSERT INTO city (province_id, city_name) VALUES
  (26, 'Kabupaten Majene'),
  (26, 'Kabupaten Mamasa'),
  (26, 'Kabupaten Mamuju'),
  (26, 'Kabupaten Mamuju Tengah'),
  (26, 'Kabupaten Mamuju Utara'),
  (26, 'Kabupaten Polewari Mandar');

INSERT INTO city (province_id, city_name) VALUES
  (27, 'Kabupaten Bantaeng'),
  (27, 'Kabupaten Barru'),
  (27, 'Kabupaten Bone'),
  (27, 'Kabupaten Bulukumba'),
  (27, 'Kabupaten Enrekang'),
  (27, 'Kabupaten Gowa'),
  (27, 'Kabupaten Jeneponto'),
  (27, 'Kabupaten Kepulauan Selayar'),
  (27, 'Kabupaten Luwu'),
  (27, 'Kabupaten Luwu Timur'),
  (27, 'Kabupaten Luwu Utara'),
  (27, 'Kabupaten Maros'),
  (27, 'Kabupaten Pangkajene dan Kepulauan'),
  (27, 'Kabupaten Pinrang'),
  (27, 'Kabupaten Sidenreng Rappang'),
  (27, 'Kabupaten Sinjai'),
  (27, 'Kabupaten Soppeng'),
  (27, 'Kabupaten Takalar'),
  (27, 'Kabupaten Tana Toraja'),
  (27, 'Kabupaten Toraja Utara'),
  (27, 'Kabupaten Wajo'),
  (27, 'Kota Makasar'),
  (27, 'Kota Palopo'),
  (27, 'Kota Parepare');

INSERT INTO city (province_id, city_name) VALUES
  (28, 'Kabupaten Banggai'),
  (28, 'Kabupaten Banggai Kepulauan'),
  (28, 'Kabupaten Banggai Laut'),
  (28, 'Kabupaten Buol'),
  (28, 'Kabupaten Donggala'),
  (28, 'Kabupaten Morowali'),
  (28, 'Kabupaten Morowali Utara'),
  (28, 'Kabupaten Parigi Moutong'),
  (28, 'Kabupaten Poso'),
  (28, 'Kabupaten Sigi'),
  (28, 'Kabupaten Tojo Una-Una'),
  (28, 'Kabupaten Tolitoli'),
  (28, 'Kota Palu');

INSERT INTO city (province_id, city_name) VALUES
  (29, 'Kabupaten Bombana'),
  (29, 'Kabupaten Buton'),
  (29, 'Kabupaten Buton Selatan'),
  (29, 'Kabupaten Buton Tengah'),
  (29, 'Kabupaten Buton Utara'),
  (29, 'Kabupaten Kolaka'),
  (29, 'Kabupaten Kolaka Timur'),
  (29, 'Kabupaten Kolaka Utara'),
  (29, 'Kabupaten Konawe'),
  (29, 'Kabupaten Konawe Kepulauan'),
  (29, 'Kabupaten Konawe Selatan'),
  (29, 'Kabupaten Konawe Utara'),
  (29, 'Kabupaten Muna'),
  (29, 'Kabupaten Muna Barat'),
  (29, 'Kabupaten Wakatobi'),
  (29, 'Kota Bau-Bau'),
  (29, 'Kota Kendari');

INSERT INTO city (province_id, city_name) VALUES
  (30, 'Kabupaten Bolaang Mongondow'),
  (30, 'Kabupaten Bolaang Mongondow Selatan'),
  (30, 'Kabupaten Bolaang Mongondow Timur'),
  (30, 'Kabupaten Bolaang Mongondow Utara'),
  (30, 'Kabupaten Kepulauan Sangihe'),
  (30, 'Kabupaten Kepulauan Siau Tagulandang Biaro'),
  (30, 'Kabupaten Kepulauan Talaud'),
  (30, 'Kabupaten Minahasa'),
  (30, 'Kabupaten Minahasa Selatan'),
  (30, 'Kabupaten Minahasa Tenggara'),
  (30, 'Kabupaten Minahasa Utara'),
  (30, 'Kota Bitung'),
  (30, 'Kota Kotamobagu'),
  (30, 'Kota Manado'),
  (30, 'Kota Tomohon');

INSERT INTO city (province_id, city_name) VALUES
  (31, 'Kabupaten Agam'),
  (31, 'Kabupaten Dharmasraya'),
  (31, 'Kabupaten Kepulauan Mentawai'),
  (31, 'Kabupaten Lima Puluh Kota'),
  (31, 'Kabupaten Padang Pariaman'),
  (31, 'Kabupaten Pasaman'),
  (31, 'Kabupaten Pasaman Barat'),
  (31, 'Kabupaten Pesisir Selatan'),
  (31, 'Kabupaten Sijunjung'),
  (31, 'Kabupaten Solok'),
  (31, 'Kabupaten Solok Selatan'),
  (31, 'Kabupaten Tanah Datar'),
  (31, 'Kota Bukittinggi'),
  (31, 'Kota Padang'),
  (31, 'Kota Padangpanjang'),
  (31, 'Kota Pariaman'),
  (31, 'Kota Payakumbuh'),
  (31, 'Kota Sawahlunto'),
  (31, 'Kota Solok');

INSERT INTO city (province_id, city_name) VALUES
  (32, 'Kabupaten Banyuasin'),
  (32, 'Kabupaten Empat Lawang'),
  (32, 'Kabupaten Lahat'),
  (32, 'Kabupaten Muara Enim'),
  (32, 'Kabupaten Musi Banyuasin'),
  (32, 'Kabupaten Musi Rawas'),
  (32, 'Kabupaten Musi Rawas Utara'),
  (32, 'Kabupaten Ogan Ilir'),
  (32, 'Kabupaten Ogan Komering Ilir'),
  (32, 'Kabupaten Ogan Komering Ulu'),
  (32, 'Kabupaten Ogan Komering Ilir Selatan'),
  (32, 'Kabupaten Ogan Komering Ilir Timur'),
  (32, 'Kabupaten Penukal Abab Lematang Ilir'),
  (32, 'Kota Lubuklinggau'),
  (32, 'Kota Pagar Alam'),
  (32, 'Kota Palembang'),
  (32, 'Kota Prabumulih');

INSERT INTO city (province_id, city_name) VALUES
  (33, 'Kabupaten Asahan'),
  (33, 'Kabupaten Batubara'),
  (33, 'Kabupaten Dairi'),
  (33, 'Kabupaten Deli Serdang'),
  (33, 'Kabupaten Humbang Hasundutan'),
  (33, 'Kabupaten Karo'),
  (33, 'Kabupaten Labuhanbatu'),
  (33, 'Kabupaten Labuhanbatu Selatan'),
  (33, 'Kabupaten Labuhanbatu Utara'),
  (33, 'Kabupaten Langkat'),
  (33, 'Kabupaten Mandailing Natal'),
  (33, 'Kabupaten Nias'),
  (33, 'Kabupaten Nias Barat'),
  (33, 'Kabupaten Nias Selatan'),
  (33, 'Kabupaten Nias Utara'),
  (33, 'Kabupaten Padang Lawas'),
  (33, 'Kabupaten Padang Lawas Utara'),
  (33, 'Kabupaten Pakpak Bharat'),
  (33, 'Kabupaten Samosir'),
  (33, 'Kabupaten Serdang Bedagai'),
  (33, 'Kabupaten Simalungun'),
  (33, 'Kabupaten Tapanuli Selatan'),
  (33, 'Kabupaten Tapanuli Tengah'),
  (33, 'Kabupaten Tapanuli Utara'),
  (33, 'Kabupaten Toba Samosir'),
  (33, 'Kota Binjai'),
  (33, 'Kota Gunungsitoli'),
  (33, 'Kota Medan'),
  (33, 'Kota Padangsidempuan'),
  (33, 'Kota Pematangsiantar'),
  (33, 'Kota Sibolga'),
  (33, 'Kota Tanjungbalai'),
  (33, 'Kota Tebing Tinggi');

INSERT INTO city (province_id, city_name) VALUES
  (34, 'Kabupaten Bantul'),
  (34, 'Kabupaten Gunungkidul'),
  (34, 'Kabupaten Kulon Progo'),
  (34, 'Kabupaten Sleman'),
  (34, 'Kota Yogyakarta');